# Markdownlint configuration for consistent README formatting
# Based on: https://github.com/DavidAnson/markdownlint

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# First line should be a top-level heading
MD041: false

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Emphasis should be used instead of bold
MD036: false

# Lists should be surrounded by blank lines
MD032: false

# Lists should be indented with 2 spaces
MD007:
  indent: 2

# Unordered list style
MD004:
  style: dash

# Ordered list style
MD029:
  style: ordered

# Code blocks should have a language specified
MD040: false

# Inline HTML
MD033: false

# Hard tabs
MD010: false

# Trailing spaces
MD009: false

# Line end
MD047: false
