name: Manifest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate manifest.json
        run: python3 scripts/validate_manifest.py

      - name: Generate README from manifest
        run: python3 scripts/manifest2readme.py

      - name: Update repository READMEs
        run: python3 scripts/update_readmes.py

      - name: Ensure READMEs are committed
        run: |
          if ! git diff --quiet; then
            echo "::error::README files are out of date. Run python3 scripts/update_readmes.py and commit the result."
            git --no-pager diff | cat
            exit 1
          fi
